apiVersion: apps/v1
kind: Deployment
metadata:
  name: poeditor-deployment
spec:
  selector:
    matchLabels:
      app: poeditor-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: poeditor-deployment
    spec:
      containers:
      - name: poeditor
        image: 875098767412.dkr.ecr.us-east-1.amazonaws.com/poeditor-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: poeditor-service
spec:
  selector:
    app: poeditor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
