# Generated by Django 4.0.2 on 2022-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(verbose_name='created date')),
            ],
        ),
    ]
